=== youngshadow/rnp-videoplayer/object.dtd
<!ELEMENT rio_object
(obj_filename,obj_filesize,obj_title,obj_type,professor,course,coursecode,grad_program,source,bitrate,duration,resolution,related_media) >
    <!ELEMENT obj_filename (#PCDATA) >
    <!ELEMENT obj_filesize (#PCDATA) >
    <!ELEMENT obj_title (#PCDATA) >
    <!ELEMENT obj_type (#PCDATA) >
    <!ELEMENT professor (#PCDATA) >
    <!ELEMENT course (#PCDATA) >
    <!ELEMENT coursecode (#PCDATA) >
    <!ELEMENT grad_program (#PCDATA) >
    <!ELEMENT source (#PCDATA) >
    <!ELEMENT bitrate (#PCDATA) >
    <!ELEMENT duration (#PCDATA) >
    <!ELEMENT resolution (r_x,r_y) >
        <!ELEMENT r_x (#PCDATA) >
        <!ELEMENT r_y (#PCDATA) >
    <!ELEMENT related_media (rm_item*) >
        <!ELEMENT rm_item (rm_filename,rm_type) >
            <!ELEMENT rm_filename (#PCDATA) >
            <!ELEMENT rm_type (#PCDATA) >

=== youngshadow/rnp-videoplayer/trunk/dcc119_aula7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rio_object SYSTEM "object.dtd">
<rio_object>
    <obj_filename>dcc119_aula7.flv</obj_filename>
    <obj_filesize>9265832</obj_filesize>
    <obj_title>Matrizes</obj_title>
    <obj_type>h.264 FLV</obj_type>
    <professor>Rodrigo Luis de Sousa da Silva</professor>
    <course>Algoritmos</course>
    <coursecode>dcc119</coursecode>
    <grad_program>CiÃªncias Exatas</grad_program>
    <source>ufjf</source>
    <bitrate>1100.0</bitrate>
    <duration>00:12:08</duration>
    <resolution>
        <r_x>320</r_x>
        <r_y>240</r_y>
    </resolution>
    <related_media>
        <rm_item>
            <rm_filename>dcc119_aula7.index</rm_filename>
            <rm_type>index</rm_type>
        </rm_item>
        <rm_item>
            <rm_filename>dcc119_aula7.flv</rm_filename>
            <rm_type>video</rm_type>
        </rm_item>
        <rm_item>
            <rm_filename>dcc119_aula7.sync</rm_filename>
            <rm_type>sync</rm_type>
        </rm_item>
    </related_media>
</rio_object>

=== youngshadow/rnp-videoplayer/trunk/dcc119_aula1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rio_object SYSTEM "object.dtd">
<rio_object>
    <obj_filename>dcc119_aula1.flv</obj_filename>
    <obj_filesize>31281530</obj_filesize>
    <obj_title>Tipos de Dados, Variáveis e Comandos de Entrada e Saída</obj_title>
    <obj_type>h.264 FLV</obj_type>
    <professor>Eduardo Barrére</professor>
    <course>Algoritmos</course>
    <coursecode>dcc119</coursecode>
    <grad_program>Ciências Exatas</grad_program>
    <source>UFJF</source>
    <bitrate>1100.0</bitrate>
    <duration>00:41:22</duration>
    <resolution>
        <r_x>320</r_x>
        <r_y>240</r_y>
    </resolution>
    <related_media>
        <rm_item>
            <rm_filename>dcc119_aula1.index</rm_filename>
            <rm_type>index</rm_type>
        </rm_item>
        <rm_item>
            <rm_filename>dcc119_aula1.flv</rm_filename>
            <rm_type>video</rm_type>
        </rm_item>
        <rm_item>
            <rm_filename>dcc119_aula1.sync</rm_filename>
            <rm_type>sync</rm_type>
        </rm_item>
    </related_media>
</rio_object>
